---

- hosts: all
  become: true
  tasks:
  - name: update repository index apt
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install the apache(httpd) package dnf
    dnf:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Install the apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Update repository index dnf
    dnf:
      update_cache: yes
    when: ansible_distribution in ["Rocky", "CentOS"]
