---

- hosts: all
  become: true
  tasks:

  - name: Install the htop package
    dnf:
      name: htop
      state: latest

  - name: Install the htop package
    apt:
      name: htop
      state: latest
