---

- hosts: all
  become: true
  tasks:

  - name: Install the apache and php package for ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install apache(httpd) and php for redhat family
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_os_family == "RedHat"
